### ISSUE TITLE
User Story: MVP - User Profile

### ISSUE THREAD

**Issue by stefrie** [cf-301-group-2021/entertainment-tracker#5]
- Title
- User Story sentence
- Feature Tasks
- Acceptance Tests

**Comment by joeivans** [comment]
Title: MVP - Simple Login
- As a user, I want to be able to log into the site using my email address and password, so that I can have a custom and persistent profile.

Feature Tasks
- Create simple login component.
- Create state in parent component for login/logout nav toggle.
- Create state in parent component for my shows nav toggle.

Acceptance Tests
- Given a home page, when user clicks the login nav item, then user should be presented with a login mechanism.
- Given that user is logged in, when user clicks logout, then user should be logged out and returned to default home page.
- Given that user is logged out, when user inspects the nav bar, they do not see logout or my shows options.
- Given that user is logged in, when user inspects the nav bar, they see logout and my shows options.

**Comment by KasonBraley** [comment]
User's can login and add tv shows to their custom collection. This data persists in the DB and rerenders with the user logs back in.
